@startuml
'https://plantuml.com/sequence-diagram

autonumber
'FRom index to order confirmation
Index -> UserController: /login
UserController -> Context : render()
Context -> login:

login -> UserController: /registerPassword get & post
UserController -> UserController :registerInfo()
UserController -> UserMapper: -> updateUser()
UserMapper _>
UserController -> Context : render()
Context -> registerInfo


@enduml