name: Notify Discord on Push

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord message
        uses: ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            🚀 **New push to `${{ github.repository }}`**
            • **Author:** ${{ github.actor }}
            • **Branch:** ${{ github.ref_name }}
            • **Commit message:** ${{ github.event.head_commit.message }}
